CREATE TABLE IF NOT EXISTS likes (
    user_id BIGINT,
    post_id BIGINT NOT NULL REFERENCES posts ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY(user_id, post_id)
);