apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-container
        image: 721145219880.dkr.ecr.eu-central-1.amazonaws.com/nearby-gateway:d057be689a8c6829ff7dc9b1914833c68619b702
        ports:
        - containerPort: 3004
        env:
          - name: USERS_SERVICE
            value: "http://users-service"
          - name: NOTIFICATIONS_SERVICE
            value: "http://notifications-service"
          - name: POSTS_SERVICE
            value: "http://posts-service"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
  type: LoadBalancer