apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer-container
        image: 721145219880.dkr.ecr.eu-central-1.amazonaws.com/nearby-mailer:c930bf2f25274026346402c602106ab482c3fdd2
        ports:
        - containerPort: 3003
        env:
          - name: SMTP_HOST
            value: "smtp.gmail.com"
          - name: SMTP_PORT
            value: "587"
          - name: SMTP_USERNAME
            value: "dev.nearby.app@gmail.com"
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-smtp-password
          - name: SMTP_SENDER
            value: "Nearby<dev.nearby.app@gmail.com>"
---
apiVersion: v1
kind: Service
metadata:
  name: mailer-service
spec:
  selector:
    app: mailer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP