apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer-container
        image: 721145219880.dkr.ecr.eu-central-1.amazonaws.com/nearby-mailer:ea837b53a87bf980619dbcbdfe08d0f395659a43
        ports:
        - containerPort: 3003
        env:
          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-smtp-host
          - name: SMTP_PORT
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-smtp-port
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-smtp-username
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-smtp-password
          - name: SMTP_SENDER
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-smtp-sender
---
apiVersion: v1
kind: Service
metadata:
  name: mailer-service
spec:
  selector:
    app: mailer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP