apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications-container
        image: 721145219880.dkr.ecr.eu-central-1.amazonaws.com/nearby-notifications:fb53a2b8db25770fc93e5bb3dbdff4dc69846c67
        ports:
        - containerPort: 3002
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-notifications-dsn
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-jwt-secret
          - name: USERS_SERVICE
            value: "http://users-service"
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP