apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts-container
        image: 721145219880.dkr.ecr.eu-central-1.amazonaws.com/nearby-posts:ea837b53a87bf980619dbcbdfe08d0f395659a43
        ports:
        - containerPort: 3001
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-posts-dsn
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-jwt-secret
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-s3-bucket-name
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-s3-region
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-s3-access-key-id
          - name: AWS_ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: nearby-s3-access-key-secret
          - name: USERS_SERVICE
            value: "http://users-service"
          - name: NOTIFICATIONS_SERVICE
            value: "http://notifications-service"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP