apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  nearby-jwt-secret: NTE0MjA2MjgtNzkyNi00MWIzLWFhMTktZTgxMzk1NzYxNDc4
  nearby-users-dsn: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRhYVExd0xheVE0RUVsUk1sb25nQG5lYXJieS5jdHF6NnRldTN0dnkuZXUtY2VudHJhbC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvbmVhcmJ5X3VzZXJz
  nearby-posts-dsn: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRhYVExd0xheVE0RUVsUk1sb25nQG5lYXJieS5jdHF6NnRldTN0dnkuZXUtY2VudHJhbC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvbmVhcmJ5X3Bvc3Rz
  nearby-notifications-dsn: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRhYVExd0xheVE0RUVsUk1sb25nQG5lYXJieS5jdHF6NnRldTN0dnkuZXUtY2VudHJhbC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvbmVhcmJ5X25vdGlmaWNhdGlvbnM=
  nearby-s3-bucket-name: bmVhcmJ5LWFwcHM=
  nearby-s3-region: ZXUtY2VudHJhbC0x
  nearby-s3-access-key-id: QUtJQTJQWjQyWk1VTkk0NkJQRVk=
  nearby-s3-access-key-secret: bkhWVDlsNDN6YWE1dGFENDU0TkpsN3MzdGVJTGdLWjZ6bUJMK1VjRgo=
  nearby-smtp-host: c210cG0uZ21haWwuY29t
  nearby-smtp-port: NTg3
  nearby-smtp-username: ZGV2Lm5lYXJieS5hcHAuZ21haWwuY29t
  nearby-smtp-password: ZG12aSBtcGhuIGdod2YgYWRxbg==
  nearby-smtp-sender: TmVhcmJ5PGRldi5uZWFyYnkuYXBwQGdtYWlsLmNvbT4=
