apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  nearby-jwt-secret: secret
  nearby-users-dsn: postgresql://postgres:taaQ1wLayQ4EElRMlong@nearby.ctqz6teu3tvy.eu-central-1.rds.amazonaws.com:5432/nearby_users
  nearby-posts-dsn: postgresql://postgres:taaQ1wLayQ4EElRMlong@nearby.ctqz6teu3tvy.eu-central-1.rds.amazonaws.com:5432/nearby_posts
  nearby-notifications-dsn: postgresql://postgres:taaQ1wLayQ4EElRMlong@nearby.ctqz6teu3tvy.eu-central-1.rds.amazonaws.com:5432/nearby_notifications
  nearby-s3-bucket-name: nearby-apps
  nearby-s3-region: eu-central-1
  nearby-s3-access-key-id: AKIA2PZ42ZMUNI46BPEY
  nearby-s3-access-key-secret: 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
  nearby-smtp-password: dmvi mphn ghwf adqn
