apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-container
        image: eu-central-1.amazonaws.com/nearby-users:be12e8d30cb5059077051453f7a6a243cd9747a6
        ports:
        - containerPort: 3000
        env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: nearby-users-dsn
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: nearby-jwt-secret
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: nearby-s3-bucket-name
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: nearby-s3-region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: nearby-s3-access-key-id
            - name: AWS_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: nearby-s3-access-key-secret
            - name: MAILER_SERVICE
              value: http://mailer-service
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP