CREATE TABLE IF NOT EXISTS tokens (
    id BIGSERIAL PRIMARY KEY,
    hash BYTEA NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    expiry TIMESTAMPTZ NOT NULL,
    type TEXT NOT NULL,
    used BOOLEAN DEFAULT FALSE
);