apiVersion: mailer/v1
kind: Deployment
metadata:
  name: mailer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer-container
        image: 721145219880.dkr.ecr.eu-central-1.amazonaws.com/nearby-mailer:latest
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: mailer-service
spec:
  selector:
    app: mailer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP