apiVersion: notifications/v1
kind: Deployment
metadata:
  name: notifications-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications-container
        image: 721145219880.dkr.ecr.eu-central-1.amazonaws.com/nearby-notifications:latest
        ports:
        - containerPort: 3002
---
  apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP