apiVersion: posts/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts-container
        image: 721145219880.dkr.ecr.eu-central-1.amazonaws.com/nearby-posts:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  selector:
    app: posts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP