name: Build image and push to ECR

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: nearby
  EKS_CLUSTER_NAME: nearby

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - users
          - posts
          - notifications
          - mailer
          - gateway
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build ./server/ -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}-${{ matrix.service }}:${{ github.sha }} -f ./server/${{ matrix.service }}/Dockerfile
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}-${{ matrix.service }}:${{ github.sha }}

  update-and-commit:
    name: Update Kubernetes Files and Commit
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Kubernetes deployment
        run: |
          for service in users posts notifications mailer gateway; do
            IMAGE_NAME=${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}-$service:${{ github.sha }}
            sed -i "s|image:.*|image: $IMAGE_NAME|" ./k8s/$service.yaml
          done

      - name: Commit and Push deployment changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --rebase
          git add ./k8s/
          git commit -m "ci: update images in Kubernetes files"
          git push
