name: Run tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'users/**'
      - 'posts/**'
      - 'notifications/**'
      - 'mailer/**'
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Test users service
      run: |
        cd server/users
        go test -v ./...

    - name: Test posts service
      run: |
        cd server/posts
        go test -v ./...

    - name: Test notifications service
      run: |
        cd server/notifications
        go test -v ./...

    - name: Test mailer service
      run: |
        cd server/mailer
        go test -v ./...
