name: Run tests

on:
  pull_request:
    paths:
      - 'users/**'
      - 'posts/**'
      - 'notifications/**'
      - 'mailer/**'
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Test users service
      if: ${{ contains(github.event.pull_request.changed_files, 'users/') }}
      run: |
        cd users
        go test -v ./...

    - name: Test posts service
      if: ${{ contains(github.event.pull_request.changed_files, 'posts/') }}
      run: |
        cd posts
        go test -v ./...

    - name: Test notifications service
      if: ${{ contains(github.event.pull_request.changed_files, 'notifications/') }}
      run: |
        cd notifications
        go test -v ./...

    - name: Test mailer service
      if: ${{ contains(github.event.pull_request.changed_files, 'mailer/') }}
      run: |
        cd mailer
        go test -v ./...
